DROP TABLE xnjia_mysalf.cb_sys_user;
CREATE TABLE xnjia_mysalf.cb_sys_user (ROW_ID int NOT NULL AUTO_INCREMENT, SORT_NO int(10) NOT NULL COMMENT '序列号,用于排序', USER_CODE varchar(32) NOT NULL COMMENT '用户编码', USER_PASSWORD varchar(500) NOT NULL COMMENT '用户密码', USER_NAME varchar(32) NOT NULL COMMENT '用户名', COMPANY_ID int(10) NOT NULL COMMENT '公司ID', NOTES varchar(200) COMMENT '备注', CREATE_TIME datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间', PRIMARY KEY (ROW_ID)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';
INSERT INTO xnjia_mysalf.cb_sys_user (ROW_ID, SORT_NO, USER_CODE, USER_PASSWORD, USER_NAME, COMPANY_ID, NOTES, CREATE_TIME) VALUES (1, 1, 'CB', '$2a$10$kLHHGhkzEdQs.T49Ghr4beRHxTEx8LROu7j.l2Wo4hhCvHGGouKAy', '菜逼', 2, '', '2017-08-24 23:28:39');
INSERT INTO xnjia_mysalf.cb_sys_user (ROW_ID, SORT_NO, USER_CODE, USER_PASSWORD, USER_NAME, COMPANY_ID, NOTES, CREATE_TIME) VALUES (2, 2, 'WCH', '9c38275b1a0cd3f8aae1c0a16fe73ba9bccf4dccedf3410a08ec5d4395343cfd77b0970b34bd9024', '武昌', 2, '', '2017-08-24 23:29:39');
INSERT INTO xnjia_mysalf.cb_sys_user (ROW_ID, SORT_NO, USER_CODE, USER_PASSWORD, USER_NAME, COMPANY_ID, NOTES, CREATE_TIME) VALUES (3, 3, 'THL', '827ccb0eea8a706c4c34a16891f84e7b', '糖葫芦', 2, '', '2017-08-24 23:29:47');


DROP TABLE xnjia_mysalf.cb_sys_user_role;
CREATE TABLE xnjia_mysalf.cb_sys_user_role (ROW_ID int NOT NULL AUTO_INCREMENT, USER_ID int(10) NOT NULL COMMENT '用户Id', ROLE_ID int(10) NOT NULL COMMENT '角色权限', NOTES varchar(200) COMMENT '备注', CREATE_TIME datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间', PRIMARY KEY (ROW_ID)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';
INSERT INTO xnjia_mysalf.cb_sys_user_role (ROW_ID, USER_ID, ROLE_ID, NOTES, CREATE_TIME) VALUES (1, 1, 1, null, '2019-07-09 00:00:00');
INSERT INTO xnjia_mysalf.cb_sys_user_role (ROW_ID, USER_ID, ROLE_ID, NOTES, CREATE_TIME) VALUES (2, 1, 2, null, '2019-07-09 00:00:00');
INSERT INTO xnjia_mysalf.cb_sys_user_role (ROW_ID, USER_ID, ROLE_ID, NOTES, CREATE_TIME) VALUES (3, 2, 2, null, '2019-07-09 00:00:00');


DROP TABLE xnjia_mysalf.cb_sys_role;
CREATE TABLE xnjia_mysalf.cb_sys_role (ROW_ID int NOT NULL AUTO_INCREMENT, ROLE_NAME varchar(32) NOT NULL COMMENT '权限', NOTES varchar(200) COMMENT '备注', CREATE_TIME datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间', PRIMARY KEY (ROW_ID)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='权限表';
INSERT INTO xnjia_mysalf.cb_sys_role (ROW_ID, ROLE_NAME, NOTES, CREATE_TIME) VALUES (1, 'ADMIN', null, '2019-07-09 00:00:00');
INSERT INTO xnjia_mysalf.cb_sys_role (ROW_ID, ROLE_NAME, NOTES, CREATE_TIME) VALUES (2, 'ROLE_USER', null, '2019-07-09 00:00:00');
